export enum ErrorCode {
  SUCCESS = 0,
  INVALID_PARAM = 10001,
  USER_NOT_FOUND = 10002,
  UNAUTHORIZED = 10003,
  FORBIDDEN = 10004,
  NOT_FOUND = 10005,
  INTERNAL_ERROR = 10006,
  DUPLICATE_ENTRY = 10007,
}

export enum ErrorType {
  SUCCESS = 'success',
  INVALID_PARAM = 'INVALID_PARAM',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
}